// Full vanilla dimension_type JSON (dimension_type/<id>.json), extracted verbatim from this
// project's actual game jar. A custom dimension clones one of these wholesale and only overrides
// a few whitelisted top-level scalar fields (see dimensionTypeExportJson in exportBundle.ts) —
// same rationale as biomeTemplates.ts: this MC version's dimension_type "attributes" data-map is
// unstable/snapshot-like enough that hand-assembling one from scratch risks a world that fails to
// load, so the untouched majority of the JSON stays exactly what a real vanilla dimension uses.
export type DimensionTypeTemplateKey = "overworld" | "nether" | "end";

export const DIMENSION_TYPE_TEMPLATE_LABELS: Record<DimensionTypeTemplateKey, string> = {
  overworld: "Overworld-like (sky, day/night cycle)",
  nether: "Nether-like (no sky, ceiling, fixed light)",
  end: "End-like (no sky, void, fixed light)",
};

export const DIMENSION_TYPE_TEMPLATES: Record<DimensionTypeTemplateKey, Record<string, unknown>> = {
  overworld: {"ambient_light":0,"attributes":{"minecraft:audio/ambient_sounds":{"mood":{"block_search_extent":8,"offset":2,"sound":"minecraft:ambient.cave","tick_delay":6000}},"minecraft:audio/background_music":{"creative":{"max_delay":24000,"min_delay":12000,"sound":"minecraft:music.creative"},"default":{"max_delay":24000,"min_delay":12000,"sound":"minecraft:music.game"}},"minecraft:gameplay/bed_rule":{"can_set_spawn":"always","can_sleep":"when_dark","error_message":{"translate":"block.minecraft.bed.no_sleep"}},"minecraft:gameplay/nether_portal_spawns_piglin":true,"minecraft:gameplay/respawn_anchor_works":false,"minecraft:visual/ambient_light_color":"#0a0a0a","minecraft:visual/cloud_color":"#ccffffff","minecraft:visual/cloud_height":192.33,"minecraft:visual/fog_color":"#c0d8ff","minecraft:visual/sky_color":"#78a7ff"},"coordinate_scale":1,"default_clock":"minecraft:overworld","has_ceiling":false,"has_ender_dragon_fight":false,"has_skylight":true,"height":384,"infiniburn":"#minecraft:infiniburn_overworld","logical_height":384,"min_y":-64,"monster_spawn_block_light_limit":0,"monster_spawn_light_level":{"type":"minecraft:uniform","max_inclusive":7,"min_inclusive":0},"timelines":"#minecraft:in_overworld"},
  nether: {"ambient_light":0.1,"attributes":{"minecraft:gameplay/bed_rule":{"can_set_spawn":"never","can_sleep":"never","explodes":true},"minecraft:gameplay/can_start_raid":false,"minecraft:gameplay/fast_lava":true,"minecraft:gameplay/piglins_zombify":false,"minecraft:gameplay/respawn_anchor_works":true,"minecraft:gameplay/sky_light_level":4,"minecraft:gameplay/snow_golem_melts":true,"minecraft:gameplay/water_evaporates":true,"minecraft:visual/ambient_light_color":"#302821","minecraft:visual/default_dripstone_particle":{"type":"minecraft:dripping_dripstone_lava"},"minecraft:visual/fog_end_distance":96,"minecraft:visual/fog_start_distance":10,"minecraft:visual/sky_light_color":"#7a7aff","minecraft:visual/sky_light_factor":0},"cardinal_light":"nether","coordinate_scale":8,"has_ceiling":true,"has_ender_dragon_fight":false,"has_fixed_time":true,"has_skylight":false,"height":256,"infiniburn":"#minecraft:infiniburn_nether","logical_height":128,"min_y":0,"monster_spawn_block_light_limit":15,"monster_spawn_light_level":7,"skybox":"none","timelines":"#minecraft:in_nether"},
  end: {"ambient_light":0.25,"attributes":{"minecraft:audio/ambient_sounds":{"mood":{"block_search_extent":8,"offset":2,"sound":"minecraft:ambient.cave","tick_delay":6000}},"minecraft:audio/background_music":{"default":{"max_delay":24000,"min_delay":6000,"replace_current_music":true,"sound":"minecraft:music.end"}},"minecraft:gameplay/bed_rule":{"can_set_spawn":"never","can_sleep":"never","explodes":true},"minecraft:gameplay/respawn_anchor_works":false,"minecraft:visual/ambient_light_color":"#3f473f","minecraft:visual/fog_color":"#181318","minecraft:visual/sky_color":"#000000","minecraft:visual/sky_light_color":"#ac60cd","minecraft:visual/sky_light_factor":0},"coordinate_scale":1,"default_clock":"minecraft:the_end","has_ceiling":false,"has_ender_dragon_fight":true,"has_fixed_time":true,"has_skylight":true,"height":256,"infiniburn":"#minecraft:infiniburn_end","logical_height":256,"min_y":0,"monster_spawn_block_light_limit":0,"monster_spawn_light_level":15,"skybox":"end","timelines":"#minecraft:in_end"},
};
